ksc_ip: "{{ hostvars['ksc']['ansible_ssh_host'] }}"
web_ip: "{{ hostvars['web']['ansible_ssh_host'] }}"
mdb_ip: "{{ hostvars['mdb']['ansible_ssh_host'] }}"
psql_ip: "{{ hostvars['psql']['ansible_ssh_host'] }}"
facts_dir: "./facts"
db_root_password_file: "{{ facts_dir }}/db_root_password.txt"
ksc_db_password_file: "{{ facts_dir }}/ksc_db_password.txt"
ksc_web_password_file: "{{ facts_dir }}/ksc_web_password.txt"
